const i = {
ZArea:path.resolve(__dirname, "src/components/ZArea/index.ts"),
ZBtn:path.resolve(__dirname, "src/components/ZBtn/index.ts"),
ZContextMenu:path.resolve(__dirname, "src/components/ZContextMenu/index.ts"),
ZDesign:path.resolve(__dirname, "src/components/ZDesign/index.ts"),
ZDrag:path.resolve(__dirname, "src/components/ZDrag/index.ts"),
ZDragEditor:path.resolve(__dirname, "src/components/ZDragEditor/index.ts"),
ZDragEditorCanvas:path.resolve(__dirname, "src/components/ZDragEditorCanvas/index.ts"),
ZGroup:path.resolve(__dirname, "src/components/ZGroup/index.ts"),
ZIcon:path.resolve(__dirname, "src/components/ZIcon/index.ts"),
ZMaterialList:path.resolve(__dirname, "src/components/ZMaterialList/index.ts"),
ZNode:path.resolve(__dirname, "src/components/ZNode/index.ts"),
ZPage:path.resolve(__dirname, "src/components/ZPage/index.ts"),
ZPageList:path.resolve(__dirname, "src/components/ZPageList/index.ts"),
ZPopup:path.resolve(__dirname, "src/components/ZPopup/index.ts"),
ZScaleController:path.resolve(__dirname, "src/components/ZScaleController/index.ts"),
ZSplitter:path.resolve(__dirname, "src/components/ZSplitter/index.ts"),
ZTextField:path.resolve(__dirname, "src/components/ZTextField/index.ts"),
ZToolbar:path.resolve(__dirname, "src/components/ZToolbar/index.ts"),
ZTree:path.resolve(__dirname, "src/components/ZTree/index.ts"),
};
const e = {
"./ZArea":"./dist/ZArea.js",
"./ZBtn":"./dist/ZBtn.js",
"./ZContextMenu":"./dist/ZContextMenu.js",
"./ZDesign":"./dist/ZDesign.js",
"./ZDrag":"./dist/ZDrag.js",
"./ZDragEditor":"./dist/ZDragEditor.js",
"./ZDragEditorCanvas":"./dist/ZDragEditorCanvas.js",
"./ZGroup":"./dist/ZGroup.js",
"./ZIcon":"./dist/ZIcon.js",
"./ZMaterialList":"./dist/ZMaterialList.js",
"./ZNode":"./dist/ZNode.js",
"./ZPage":"./dist/ZPage.js",
"./ZPageList":"./dist/ZPageList.js",
"./ZPopup":"./dist/ZPopup.js",
"./ZScaleController":"./dist/ZScaleController.js",
"./ZSplitter":"./dist/ZSplitter.js",
"./ZTextField":"./dist/ZTextField.js",
"./ZToolbar":"./dist/ZToolbar.js",
"./ZTree":"./dist/ZTree.js"
}